version: '3.7'

services:
#   For when we move to postgres
    db:
      image: postgres:12.4
      restart: always
      ports:
        - '5432:5432'
      environment:
        POSTGRES_DB: LancerApp_Postgres
        POSTGRES_PASSWORD: mickeyMantle
        POSTGRES_USER: admin

#When I add keycloak
#  sso:
#    image: jboss/keycloak:12.0.1
#    restart: always
#    ports:
#      - 10000:8080
#    volumes:
#      - ./docker/keycloak/mysquad-realm.json:/tmp/mysquad-realm.json
#    command: -Dkeycloak.profile.feature.upload_scripts=enabled
#    environment:
#      - KEYCLOAK_USER=admin
#      - KEYCLOAK_PASSWORD=password
#      - KEYCLOAK_IMPORT=/tmp/mysquad-realm.json
#      - DB_VENDOR=h2
