spring:
  data:
    rest:
      base-path: /api
  datasource:
    # CONNECTION_POSTGRES_URL
    url: jdbc:postgresql://${Lancer_HOSTNAME:localhost}:${Lancer_PORT:5432}/${Lancer_DB_NAME:LancerApp_DB_Postgresql}
#    driver-class-name: org.h2.Driver
    username: ${Lancer_username:machine}
    password: ${Lancer_password:mickeyMantle}
    driver-class-name: org.postgresql.Driver
  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
  # Testing with Postgres
  #    username: todo
  #    password: todo
#    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: none
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: never
  flyway:
    locations: classpath:/db/migration
    ignore-missing-migrations: false
    out-of-order: true
    baseline-on-migrate: true
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

