spring:
  data:
    rest:
      base-path: /api
  datasource:
    url: jdbc:postgresql://localhost:5432/LancerApp_Postgres_Local
#    driver-class-name: org.h2.Driver
    username: alex
    password: mickeyMantle
    driver-class-name: org.postgresql.Driver
  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
  # Testing with Postgres
  #    username: todo
  #    password: todo
#    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: none
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: never
  flyway:
    locations: classpath:/db/migration
    ignore-missing-migrations: false
    out-of-order: true
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

